export const SITE_CONFIG = {
  name: 'NIVA',
  title: 'NIVA — Stranger Chat & Stranger Cam Semarang | Random 1-on-1',
  tagline: 'Meet a Stranger. Start a Conversation.',
  descriptor: 'Platform Stranger Chat & Stranger Cam 1-on-1 Komunitas Semarang',
  description: 'NIVA adalah platform Stranger Chat dan Stranger Cam 1-on-1 untuk komunitas Semarang. 18+, privacy-first, moderated, tanpa registrasi untuk fitur stranger.',
  url: 'https://niva.id',
  telegramBotUrl: process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL || 'https://t.me/nivasocialmakingbot',
  region: 'Semarang, Jawa Tengah, Indonesia',
  independentNotice: 'NIVA adalah platform independen yang dirancang untuk komunitas Semarang dan tidak berafiliasi, disponsori, atau dioperasikan oleh universitas mana pun.',
};

export const SEMARANG_INSTITUTIONS = [
  { id: 'inst-undip', shortName: 'UNDIP', fullName: 'Universitas Diponegoro', type: 'PTN', area: 'Tembalang / Pleburan' },
  { id: 'inst-unnes', shortName: 'UNNES', fullName: 'Universitas Negeri Semarang', type: 'PTN', area: 'Sekaran, Gunungpati' },
  { id: 'inst-uin-walisongo', shortName: 'UIN Walisongo', fullName: 'Universitas Islam Negeri Walisongo', type: 'PTN', area: 'Ngaliyan' },
  { id: 'inst-udinus', shortName: 'UDINUS', fullName: 'Universitas Dian Nuswantoro', type: 'PTS', area: 'Semarang Tengah' },
  { id: 'inst-unissula', shortName: 'UNISSULA', fullName: 'Universitas Islam Sultan Agung', type: 'PTS', area: 'Genuk' },
  { id: 'inst-unika', shortName: 'UNIKA', fullName: 'Universitas Katolik Soegijapranata (SCU)', type: 'PTS', area: 'Bendan Dhuwur / BSB' },
  { id: 'inst-unimus', shortName: 'UNIMUS', fullName: 'Universitas Muhammadiyah Semarang', type: 'PTS', area: 'Kedungmundu' },
  { id: 'inst-usm', shortName: 'USM', fullName: 'Universitas Semarang', type: 'PTS', area: 'Tlogosari' },
  { id: 'inst-unwahas', shortName: 'UNWAHAS', fullName: 'Universitas Wahid Hasyim', type: 'PTS', area: 'Sampangan / Gunungpati' },
  { id: 'inst-upgris', shortName: 'UPGRIS', fullName: 'Universitas PGRI Semarang', type: 'PTS', area: 'Sidodadi' },
  { id: 'inst-unisbank', shortName: 'UNISBANK', fullName: 'Universitas Stikubank', type: 'PTS', area: 'Mugassari / Kendeng' },
  { id: 'inst-unaki', shortName: 'UNAKI', fullName: 'Universitas AKI', type: 'PTS', area: 'Semarang Tengah' },
  { id: 'inst-ivet', shortName: 'Univ. Ivet', fullName: 'Universitas Ivet Semarang', type: 'PTS', area: 'Gajahmungkur' },
  { id: 'inst-unkaha', shortName: 'UNH', fullName: 'Universitas Karya Husada Semarang', type: 'PTS', area: 'Kompol Maksum' },
  { id: 'inst-telogorejo', shortName: 'Univ. Telogorejo', fullName: 'Universitas Telogorejo Semarang', type: 'PTS', area: 'Puri Anjasmoro' },
  { id: 'inst-stekom', shortName: 'STEKOM', fullName: 'Universitas STEKOM', type: 'PTS', area: 'Majapahit' },
  { id: 'inst-pandanaran', shortName: 'UNPAND', fullName: 'Universitas Pandanaran', type: 'PTS', area: 'Banjarsari' },
  { id: 'inst-untag', shortName: 'UNTAG', fullName: 'Universitas 17 Agustus 1945 Semarang', type: 'PTS', area: 'Bendan Dhuwur' },
  { id: 'inst-polines', shortName: 'POLINES', fullName: 'Politeknik Negeri Semarang', type: 'PTN', area: 'Tembalang' },
  { id: 'inst-polimarin', shortName: 'POLIMARIN', fullName: 'Politeknik Maritim Negeri Indonesia', type: 'PTN', area: 'Bendan Dhuwur' },
  { id: 'inst-polpu', shortName: 'Politeknik PU', fullName: 'Politeknik Pekerjaan Umum', type: 'PTK', area: 'Tembalang' },
  { id: 'inst-pip', shortName: 'PIP Semarang', fullName: 'Politeknik Ilmu Pelayaran Semarang', type: 'PTK', area: 'Singosari' },
  { id: 'inst-akpol', shortName: 'AKPOL', fullName: 'Akademi Kepolisian RI', type: 'PTK', area: 'Gajahmungkur' },
  { id: 'inst-polteka', shortName: 'POLTEKA', fullName: 'Politeknik Katolik Mangunwijaya', type: 'PTS', area: 'Semarang' },
  { id: 'inst-poltekkes', shortName: 'Poltekkes Semarang', fullName: 'Politeknik Kesehatan Kemenkes Semarang', type: 'PTN', area: 'Tirto Agung, Tembalang' },
  { id: 'inst-st-elisabeth', shortName: 'STIKES St. Elisabeth', fullName: 'STIKES St. Elisabeth Semarang', type: 'PTS', area: 'Kawi' },
  { id: 'inst-hakli', shortName: 'STIKES Hakli', fullName: 'STIKES Hakli Semarang', type: 'PTS', area: 'Dr. Cipto' },
  { id: 'inst-kesdam', shortName: 'STIKES Kesdam', fullName: 'STIKES Kesdam IV/Diponegoro', type: 'PTS', area: 'HOS Cokroaminoto' },
  { id: 'inst-stifar', shortName: 'STIFAR', fullName: 'Sekolah Tinggi Ilmu Farmasi Semarang', type: 'PTS', area: 'Menoreh' },
  { id: 'inst-stikes-smg', shortName: 'STIKES Semarang', fullName: 'STIKES Semarang', type: 'PTS', area: 'Pedurungan' },
  { id: 'inst-widya-husada', shortName: 'UWHS', fullName: 'Universitas Widya Husada Semarang', type: 'PTS', area: 'Subali Raya / Krapyak' },
  { id: 'inst-binatrada', shortName: 'Bina Trada', fullName: 'Politeknik Bina Trada Semarang', type: 'PTS', area: 'Semarang' },
  { id: 'inst-stibisnis', shortName: 'STiBISNIS', fullName: 'Politeknik STiBISNIS Semarang', type: 'PTS', area: 'Semarang' },
];

export const FIXED_INSTITUTION_COUNT = 33;

