export const SITE_CONFIG = {
  name: 'NIVA',
  title: 'NIVA — Student Social & Matchmaking Platform in Semarang',
  tagline: 'Meet someone worth knowing.',
  descriptor: 'Student Social & Matchmaking Platform',
  description: 'NIVA helps verified students discover meaningful connections, shared interests, and new conversations across the Semarang campus community. 18+ and privacy-focused.',
  url: 'https://niva.id',
  telegramBotUrl: process.env.NEXT_PUBLIC_TELEGRAM_BOT_URL || 'https://t.me/nivasocialmakingbot',
  region: 'Semarang, Jawa Tengah, Indonesia',
  independentNotice: 'NIVA adalah platform independen yang dirancang untuk mahasiswa dan tidak berafiliasi, disponsori, atau dioperasikan oleh universitas mana pun.',
};

export const SEMARANG_INSTITUTIONS = [
  { shortName: 'UNDIP', fullName: 'Universitas Diponegoro', type: 'PTN', area: 'Tembalang / Pleburan' },
  { shortName: 'UNNES', fullName: 'Universitas Negeri Semarang', type: 'PTN', area: 'Sekaran, Gunungpati' },
  { shortName: 'UIN Walisongo', fullName: 'Universitas Islam Negeri Walisongo', type: 'PTN', area: 'Ngaliyan' },
  { shortName: 'UDINUS', fullName: 'Universitas Dian Nuswantoro', type: 'PTS', area: 'Semarang Tengah' },
  { shortName: 'UNISSULA', fullName: 'Universitas Islam Sultan Agung', type: 'PTS', area: 'Genuk' },
  { shortName: 'UNIKA', fullName: 'Universitas Katolik Soegijapranata (SCU)', type: 'PTS', area: 'Bendan Dhuwur / BSB' },
  { shortName: 'UNIMUS', fullName: 'Universitas Muhammadiyah Semarang', type: 'PTS', area: 'Kedungmundu' },
  { shortName: 'USM', fullName: 'Universitas Semarang', type: 'PTS', area: 'Tlogosari' },
  { shortName: 'UNWAHAS', fullName: 'Universitas Wahid Hasyim', type: 'PTS', area: 'Sampangan / Gunungpati' },
  { shortName: 'UPGRIS', fullName: 'Universitas PGRI Semarang', type: 'PTS', area: 'Sidodadi' },
  { shortName: 'UNISBANK', fullName: 'Universitas Stikubank', type: 'PTS', area: 'Mugassari / Kendeng' },
  { shortName: 'UNAKI', fullName: 'Universitas AKI', type: 'PTS', area: 'Semarang Tengah' },
  { shortName: 'Univ. Ivet', fullName: 'Universitas Ivet Semarang', type: 'PTS', area: 'Gajahmungkur' },
  { shortName: 'UNH', fullName: 'Universitas Karya Husada Semarang', type: 'PTS', area: 'Kompol Maksum' },
  { shortName: 'Univ. Telogorejo', fullName: 'Universitas Telogorejo Semarang', type: 'PTS', area: 'Puri Anjasmoro' },
  { shortName: 'STEKOM', fullName: 'Universitas STEKOM', type: 'PTS', area: 'Majapahit' },
  { shortName: 'UNPAND', fullName: 'Universitas Pandanaran', type: 'PTS', area: 'Banjarsari' },
  { shortName: 'UNTAG', fullName: 'Universitas 17 Agustus 1945 Semarang', type: 'PTS', area: 'Bendan Dhuwur' },
  { shortName: 'POLINES', fullName: 'Politeknik Negeri Semarang', type: 'PTN', area: 'Tembalang' },
  { shortName: 'POLIMARIN', fullName: 'Politeknik Maritim Negeri Indonesia', type: 'PTN', area: 'Bendan Dhuwur' },
  { shortName: 'Politeknik PU', fullName: 'Politeknik Pekerjaan Umum', type: 'PTK', area: 'Tembalang' },
  { shortName: 'PIP Semarang', fullName: 'Politeknik Ilmu Pelayaran Semarang', type: 'PTK', area: 'Singosari' },
  { shortName: 'AKPOL', fullName: 'Akademi Kepolisian RI', type: 'PTK', area: 'Gajahmungkur' },
  { shortName: 'POLTEKA', fullName: 'Politeknik Katolik Mangunwijaya', type: 'PTS', area: 'Semarang' },
  { shortName: 'Poltekkes Semarang', fullName: 'Politeknik Kesehatan Kemenkes Semarang', type: 'PTN', area: 'Tirto Agung, Tembalang' },
  { shortName: 'STIKES St. Elisabeth', fullName: 'STIKES St. Elisabeth Semarang', type: 'PTS', area: 'Kawi' },
  { shortName: 'STIKES Hakli', fullName: 'STIKES Hakli Semarang', type: 'PTS', area: 'Dr. Cipto' },
  { shortName: 'STIKES Kesdam', fullName: 'STIKES Kesdam IV/Diponegoro', type: 'PTS', area: 'HOS Cokroaminoto' },
  { shortName: 'STIFAR', fullName: 'Sekolah Tinggi Ilmu Farmasi Semarang', type: 'PTS', area: 'Menoreh' },
  { shortName: 'UWHS', fullName: 'Universitas Widya Husada Semarang', type: 'PTS', area: 'Subali Raya' },
  { shortName: 'Bina Trada', fullName: 'Politeknik Bina Trada Semarang', type: 'PTS', area: 'Semarang' },
  { shortName: 'STiBISNIS', fullName: 'Politeknik STiBISNIS Semarang', type: 'PTS', area: 'Semarang' },
];
